package com.ridesaathi.app

object Words {
  private val en =
          mapOf(
                  "searchDestinations" to "Choose your destination",
                  "searchQuery" to "Place name and area",
                  "searchingDestination" to "Searching for places…",
                  "searchLocationRequired" to "We need your current location to find nearby places. Allow location access, turn on Location, and try again.",
                  "searchChoose" to "Which place do you mean?",
                  "searchChoiceHint" to "Say one, two, or three, or tap a place. Say “search again” to change the place.",
                  "searchMoreHint" to "Say “more results” for other options.",
                  "searchMore" to "More results",
                  "searchPrevious" to "Previous results",
                  "searchAgain" to "Search again",
                  "searchRepeat" to "Repeat options",
                  "searchNoMore" to "There are no more results. Say “search again” to try a different name or area.",
                  "searchClearer" to "Say or type the place name, with its area or city.",
                  "searchChoiceUnclear" to "Please say the number of one of these places, or tap it.",
                  "searchNoResults" to "No matching places found nearby. Try a nearby place name or area.",
                  "searchInterrupted" to "Search paused. Tap Try again to continue.",
                  "hello" to "Hello",
                  "setupHint" to "A little setup, for easier journeys. A family member can help you get started.",
                  "voiceHint" to "Tell us where you want to go.",
                  "tapHint" to "Or tap a place below to get started.",
                  "handoffHint" to "You’ll choose your ride and complete your booking in Uber.",
                  "welcome" to "Welcome to Ride Saathi",
                  "language" to "Choose your language",
                  "name" to "Your name",
                  "continue" to "Continue",
                  "homeRequired" to "Add your Home to continue",
                  "home" to "Home",
                  "addHome" to "Add Home",
                  "addPlace" to "Add another saved place",
                  "finish" to "Finish setup",
                  "uberInstall" to "Install Uber before requesting a ride",
                  "install" to "Open Play Store",
                  "places" to "Saved places",
                  "settings" to "Settings",
                  "rideTo" to "Where do you want to go?",
                  "speak" to "Speak",
                  "listening" to "Listening…",
                  "recognizedSpeech" to "Recognized speech",
                  "heardSoFar" to "Heard so far…",
                  "cancel" to "Cancel",
                  "confirm" to "Is this your destination?",
                  "yes" to "Yes, open Uber",
                  "no" to "No, choose again",
                  "working" to "Getting your current location…",
                  "locationDenied" to "Allow location to set your pickup point.",
                  "locationUnavailable" to
                          "We could not get your current location. Check Location and try again.",
                  "retry" to "Try again",
                  "unknown" to "I could not find that saved place. Choose one below.",
                  "ambiguous" to "Which saved place did you mean?",
                  "speechFailed" to "I did not catch that. Try again or tap a place.",
                  "micDenied" to "Allow microphone access to speak, or tap a place below.",
                  "placeName" to "Place name",
                  "placeNameHint" to "Use the name you’ll say when asking for a ride.",
                  "editPlace" to "Edit place",
                  "changeAddress" to "Change address",
                  "selectAddress" to "Tap the correct address below.",
                  "openAppSettings" to "Open app permissions",
                  "storeUnavailable" to "Open the Play Store on your phone and search for Uber.",
                  "rideInterrupted" to "Ride request paused. Check the destination and try again.",
                  "search" to "Search address",
                  "addressSearchHint" to "Type at least 3 characters to search automatically.",
                  "searchPending" to "Search starts when you pause typing…",
                  "searchingAddress" to "Searching addresses…",
                  "address" to "Address",
                  "save" to "Save place",
                  "delete" to "Delete place",
                  "duplicate" to "This name is already used.",
                  "invalidPlace" to "Choose an address from search first.",
                  "replaceHome" to "Replace Home before removing it.",
                  "edit" to "Edit",
                  "done" to "Done",
                  "handoffFailed" to "Uber could not open. Try again.",
                  "offline" to "Search needs internet. Try again later.",
                  "changeLanguage" to "Language",
                  "manage" to "Manage places",
                  "back" to "Back",
                  "configured" to "Address search is not set up yet. Ask the person who installed the app for help.",
                  "searchAttribution" to "Search powered by Ola Maps",
                  "searchAccessDenied" to "Address search could not connect to Ola Maps. Ask the person who installed the app for help.",
                  "searchQuota" to "Address search has reached its usage limit. Try again later.",
                  "searchUnavailable" to "Address search is temporarily unavailable. Please try again.",
                  "choosePlace" to "Choose a saved place",
                  "stop" to "Stop listening",
                  "wait" to "Please wait",
                  "voiceUnavailable" to "Voice service is unavailable. Tap a saved place.",
                  "openLocation" to "Open location settings",
                  "noResults" to "No matching address found nearby. Try a nearby place name or area.",
                  "mapAttribution" to "Map data © OpenStreetMap",
                  "providerSettings" to "Family setup: map services",
                  "searchService" to "Address search service URL",
                  "mapService" to "Map preview service URL",
                  "invalidService" to "Enter valid HTTPS service URLs.",
                  "saveServices" to "Save service URLs",
                  "servicesSaved" to "Service URLs saved.",
                  "mapUnavailable" to "The map could not load. Check your connection and try again.",
                  "showMore" to "Show more",
                  "showLess" to "Show less",
                  "sharedLocation" to "Shared location",
                  "invalidSharedLocation" to "That message does not contain a supported location. Share a location or a Google Maps link with Ride Saathi.",
                  "sharedLocationSetup" to "Finish Ride Saathi setup before using a shared location.",
                  "resolvingSharedLocation" to "Opening shared location…",
                  "selectSharedLocation" to "Select the shared destination",
                  "sharedSearchHint" to "The link includes an address. Check these search results and select the correct place.",
                  "sharedLocationOffline" to "Could not open the Google Maps link. Check your internet connection and share it again.",
                  "sharedLocationUnresolved" to "Could not find a destination pin in that link. In Google Maps, select a place or drop a pin, then share it again.",
                  "watchIntro" to "How Ride Saathi helps",
                  "watchTutorial" to "Watch tutorial",
                  "introTitle" to "Before we set up",
                  "tutorialTitle" to "How to request a ride",
                  "introFamilyTitle" to "Family sets it up once",
                  "introFamilyBody" to "A family member can add your Home and your regular places.",
                  "introPlacesTitle" to "Then rides are simpler",
                  "introPlacesBody" to "After setup, you can speak or tap a saved place to start.",
                  "tutorialSpeakTitle" to "Say or tap a place",
                  "tutorialSpeakBody" to "Say a saved place like Doctor, or tap the place name on the screen.",
                  "tutorialConfirmTitle" to "Check the destination",
                  "tutorialConfirmBody" to "Ride Saathi asks you to confirm the place before doing anything else.",
                  "tutorialPickupTitle" to "Pickup is your current location",
                  "tutorialPickupBody" to "Ride Saathi uses your phone location only to fill the pickup point.",
                  "tutorialUberTitle" to "Finish in Uber",
                  "tutorialUberBody" to "Uber opens with the destination filled. Choose the ride and book inside Uber.",
                  "replayAudio" to "Hear this again",
                  "skipTutorial" to "Skip",
                  "continueSetup" to "Continue setup",
                  "startUsing" to "Start using Ride Saathi"
          )
  private val hi =
          mapOf(
                  "searchDestinations" to "अपनी मंज़िल चुनें",
                  "searchQuery" to "जगह का नाम और इलाका",
                  "searchingDestination" to "जगह खोज रहे हैं…",
                  "searchLocationRequired" to "आस-पास की जगहें खोजने के लिए आपकी अभी की लोकेशन चाहिए। लोकेशन की अनुमति दें, लोकेशन चालू करें और फिर कोशिश करें।",
                  "searchChoose" to "आप कौन सी जगह जाना चाहते हैं?",
                  "searchChoiceHint" to "एक, दो या तीन बोलें, या जगह पर टैप करें। जगह बदलने के लिए “फिर खोजें” बोलें।",
                  "searchMoreHint" to "बाकी जगहों के लिए “और नतीजे” बोलें।",
                  "searchMore" to "और नतीजे",
                  "searchPrevious" to "पिछले नतीजे",
                  "searchAgain" to "फिर खोजें",
                  "searchRepeat" to "फिर सुनाएँ",
                  "searchNoMore" to "और नतीजे नहीं हैं। दूसरे नाम या इलाके के लिए “फिर खोजें” बोलें।",
                  "searchClearer" to "जगह का नाम और उसका इलाका या शहर बोलें या लिखें।",
                  "searchChoiceUnclear" to "इन जगहों में से किसी एक का नंबर बोलें, या उस पर टैप करें।",
                  "searchNoResults" to "आस-पास कोई जगह नहीं मिली। आस-पास की जगह या इलाके के नाम से फिर खोजें।",
                  "searchInterrupted" to "खोज रुक गई है। जारी रखने के लिए फिर कोशिश करें।",
                  "searchAttribution" to "पते की खोज: Ola Maps",
                  "searchAccessDenied" to "Ola Maps से संपर्क नहीं हो सका। ऐप इंस्टॉल करने वाले व्यक्ति से मदद लें।",
                  "searchQuota" to "पते की खोज की उपयोग सीमा पूरी हो गई है। बाद में फिर कोशिश करें।",
                  "searchUnavailable" to "पते की खोज अभी उपलब्ध नहीं है। फिर कोशिश करें।",
                  "hello" to "नमस्ते",
                  "setupHint" to "आसान सफ़र के लिए छोटा सा सेटअप। परिवार का कोई सदस्य मदद कर सकता है।",
                  "voiceHint" to "जहाँ जाना है उस जगह का नाम बोलें।",
                  "tapHint" to "या शुरू करने के लिए नीचे कोई जगह चुनें।",
                  "handoffHint" to "अपनी सवारी चुनें और बुकिंग Uber में पूरी करें।",
                  "welcome" to "राइड साथी में आपका स्वागत है",
                  "language" to "अपनी भाषा चुनें",
                  "name" to "आपका नाम",
                  "continue" to "आगे बढ़ें",
                  "homeRequired" to "आगे बढ़ने के लिए घर जोड़ें",
                  "home" to "घर",
                  "addHome" to "घर जोड़ें",
                  "addPlace" to "एक और जगह जोड़ें",
                  "finish" to "सेटअप पूरा करें",
                  "uberInstall" to "यात्रा के लिए Uber इंस्टॉल करें",
                  "install" to "Play Store खोलें",
                  "places" to "चुनी गई जगहें",
                  "settings" to "सेटिंग्स",
                  "rideTo" to "आप कहाँ जाना चाहते हैं?",
                  "speak" to "बोलें",
                  "listening" to "सुन रहे हैं…",
                  "recognizedSpeech" to "ऐप ने यह सुना",
                  "heardSoFar" to "अब तक सुना…",
                  "cancel" to "रद्द करें",
                  "confirm" to "क्या यही आपकी मंज़िल है?",
                  "yes" to "हाँ, Uber खोलें",
                  "no" to "नहीं, फिर चुनें",
                  "working" to "आपकी अभी की लोकेशन ढूँढ रहे हैं…",
                  "locationDenied" to "पिकअप के लिए आपकी अभी की लोकेशन चाहिए। इसकी अनुमति दें।",
                  "locationUnavailable" to
                          "आपकी अभी की लोकेशन नहीं मिली। लोकेशन चेक करें और फिर कोशिश करें।",
                  "retry" to "फिर कोशिश करें",
                  "unknown" to "यह जगह चुनी हुई जगहों में नहीं है। नीचे से चुनें।",
                  "ambiguous" to "आप किस जगह जाना चाहते हैं?",
                  "speechFailed" to "आवाज़ समझ नहीं आई। फिर बोलें या जगह चुनें।",
                  "micDenied" to "बोलने के लिए माइक्रोफ़ोन की अनुमति दें, या नीचे से जगह चुनें।",
                  "placeName" to "जगह का नाम",
                  "placeNameHint" to "वह नाम लिखें जो आप सवारी माँगते समय बोलेंगे।",
                  "editPlace" to "जगह बदलें",
                  "changeAddress" to "पता बदलें",
                  "selectAddress" to "नीचे सही पते पर टैप करें।",
                  "openAppSettings" to "ऐप की अनुमतियाँ खोलें",
                  "storeUnavailable" to "अपने फ़ोन पर Play Store खोलें और Uber खोजें।",
                  "rideInterrupted" to "यात्रा का अनुरोध रुक गया। जगह जाँचें और फिर कोशिश करें।",
                  "search" to "पता खोजें",
                  "addressSearchHint" to "अपने आप खोजने के लिए कम से कम 3 अक्षर लिखें।",
                  "searchPending" to "आपके लिखना रोकने पर खोज शुरू होगी…",
                  "searchingAddress" to "पते खोज रहे हैं…",
                  "address" to "पता",
                  "save" to "जगह सेव करें",
                  "delete" to "जगह हटाएँ",
                  "duplicate" to "यह नाम पहले से है।",
                  "invalidPlace" to "पहले खोज में से कोई पता चुनें।",
                  "replaceHome" to "घर हटाने से पहले नया घर जोड़ें।",
                  "edit" to "बदलें",
                  "done" to "हो गया",
                  "handoffFailed" to "Uber नहीं खुला। फिर कोशिश करें।",
                  "offline" to "खोज के लिए इंटरनेट चाहिए। बाद में कोशिश करें।",
                  "changeLanguage" to "भाषा",
                  "manage" to "जगहें बदलें",
                  "back" to "वापस",
                  "configured" to "पता खोज अभी सेट नहीं है।",
                  "choosePlace" to "चुनी गई जगह चुनें",
                  "stop" to "सुनना बंद करें",
                  "wait" to "कृपया प्रतीक्षा करें",
                  "voiceUnavailable" to "आवाज़ की सुविधा नहीं चल रही। नीचे से जगह चुनें।",
                  "openLocation" to "लोकेशन सेटिंग्स खोलें",
                  "noResults" to "आस-पास पता नहीं मिला। आस-पास की जगह या इलाके के नाम से फिर खोजें।",
                  "mapAttribution" to "नक्शे का डेटा © OpenStreetMap योगदानकर्ता",
                  "providerSettings" to "परिवार सेटअप: नक्शा सेवाएँ",
                  "searchService" to "पता खोज सेवा URL",
                  "mapService" to "नक्शा सेवा URL",
                  "invalidService" to "मान्य HTTPS सेवा URL डालें।",
                  "saveServices" to "सेवा URL सेव करें",
                  "servicesSaved" to "सेवा URL सेव हो गए।",
                  "mapUnavailable" to "नक्शा नहीं खुला। इंटरनेट चेक करें और फिर कोशिश करें।",
                  "showMore" to "और देखें",
                  "showLess" to "कम देखें",
                  "sharedLocation" to "शेयर की गई लोकेशन",
                  "invalidSharedLocation" to "इस संदेश में लोकेशन नहीं मिली। Ride Saathi के साथ लोकेशन या Google Maps लिंक शेयर करें।",
                  "sharedLocationSetup" to "शेयर की गई लोकेशन इस्तेमाल करने से पहले Ride Saathi का सेटअप पूरा करें।",
                  "resolvingSharedLocation" to "शेयर की गई लोकेशन खोली जा रही है…",
                  "selectSharedLocation" to "शेयर की गई मंज़िल चुनें",
                  "sharedSearchHint" to "लिंक में पता मिला है। खोज के नतीजे जाँचें और सही जगह चुनें।",
                  "sharedLocationOffline" to "Google Maps लिंक नहीं खुल सका। इंटरनेट कनेक्शन जाँचें और फिर से शेयर करें।",
                  "sharedLocationUnresolved" to "इस लिंक में मंज़िल का पिन नहीं मिला। Google Maps में कोई जगह चुनें या पिन लगाएँ, फिर से शेयर करें।",
                  "watchIntro" to "Ride Saathi कैसे मदद करता है",
                  "watchTutorial" to "ट्यूटोरियल देखें",
                  "introTitle" to "सेटअप से पहले",
                  "tutorialTitle" to "राइड कैसे माँगें",
                  "introFamilyTitle" to "परिवार एक बार सेटअप करता है",
                  "introFamilyBody" to "परिवार का कोई सदस्य आपका घर और रोज़ जाने वाली जगहें जोड़ सकता है।",
                  "introPlacesTitle" to "फिर राइड आसान हो जाती है",
                  "introPlacesBody" to "सेटअप के बाद, शुरू करने के लिए जगह बोलें या उस पर टैप करें।",
                  "tutorialSpeakTitle" to "जगह बोलें या टैप करें",
                  "tutorialSpeakBody" to "Doctor जैसी सेव की हुई जगह बोलें, या स्क्रीन पर जगह का नाम टैप करें।",
                  "tutorialConfirmTitle" to "मंज़िल जाँचें",
                  "tutorialConfirmBody" to "Ride Saathi आगे बढ़ने से पहले आपसे जगह कन्फर्म करवाता है।",
                  "tutorialPickupTitle" to "पिकअप आपकी अभी की लोकेशन है",
                  "tutorialPickupBody" to "Ride Saathi पिकअप भरने के लिए सिर्फ़ आपके फ़ोन की लोकेशन इस्तेमाल करता है।",
                  "tutorialUberTitle" to "Uber में पूरा करें",
                  "tutorialUberBody" to "Uber मंज़िल के साथ खुलता है। राइड चुनें और बुकिंग Uber में करें।",
                  "replayAudio" to "फिर सुनें",
                  "skipTutorial" to "छोड़ें",
                  "continueSetup" to "सेटअप जारी रखें",
                  "startUsing" to "Ride Saathi शुरू करें"
          )
  private val te =
          mapOf(
                  "searchDestinations" to "మీ గమ్యస్థానాన్ని ఎంచుకోండి",
                  "searchQuery" to "స్థలం పేరు మరియు ప్రాంతం",
                  "searchingDestination" to "స్థలాలను వెతుకుతున్నాం…",
                  "searchLocationRequired" to "దగ్గరలోని స్థలాలను వెతకడానికి మీ ప్రస్తుత స్థానం కావాలి. లొకేషన్ అనుమతి ఇచ్చి, లొకేషన్ ఆన్ చేసి మళ్లీ ప్రయత్నించండి.",
                  "searchChoose" to "మీరు ఏ స్థలానికి వెళ్లాలనుకుంటున్నారు?",
                  "searchChoiceHint" to "ఒకటి, రెండు లేదా మూడు చెప్పండి, లేదా స్థలాన్ని నొక్కండి. స్థలం మార్చడానికి “మళ్లీ వెతకండి” అని చెప్పండి.",
                  "searchMoreHint" to "ఇతర స్థలాల కోసం “మరిన్ని ఫలితాలు” అని చెప్పండి.",
                  "searchMore" to "మరిన్ని ఫలితాలు",
                  "searchPrevious" to "మునుపటి ఫలితాలు",
                  "searchAgain" to "మళ్లీ వెతకండి",
                  "searchRepeat" to "మళ్లీ వినిపించండి",
                  "searchNoMore" to "ఇంకా ఫలితాలు లేవు. వేరే పేరు లేదా ప్రాంతంతో ప్రయత్నించడానికి “మళ్లీ వెతకండి” అని చెప్పండి.",
                  "searchClearer" to "స్థలం పేరు, దాని ప్రాంతం లేదా నగరం చెప్పండి లేదా టైప్ చేయండి.",
                  "searchChoiceUnclear" to "ఈ స్థలాల్లో ఒకదాని సంఖ్య చెప్పండి, లేదా దాన్ని నొక్కండి.",
                  "searchNoResults" to "దగ్గరలో సరిపోయే స్థలాలు దొరకలేదు. దగ్గరలోని స్థలం లేదా ప్రాంతం పేరుతో మళ్లీ వెతకండి.",
                  "searchInterrupted" to "వెతుకులాట ఆగిపోయింది. కొనసాగించడానికి మళ్లీ ప్రయత్నించండి.",
                  "searchAttribution" to "చిరునామా శోధన: Ola Maps",
                  "searchAccessDenied" to "Ola Mapsతో కనెక్ట్ కాలేదు. యాప్ ఇన్‌స్టాల్ చేసిన వ్యక్తి సహాయం తీసుకోండి.",
                  "searchQuota" to "చిరునామా శోధన వినియోగ పరిమితి చేరుకుంది. తర్వాత మళ్లీ ప్రయత్నించండి.",
                  "searchUnavailable" to "చిరునామా శోధన ప్రస్తుతం అందుబాటులో లేదు. మళ్లీ ప్రయత్నించండి.",
                  "placeNameHint" to "రైడ్ అడిగేటప్పుడు మీరు చెప్పే పేరును వాడండి.",
                  "editPlace" to "స్థలాన్ని మార్చండి",
                  "changeAddress" to "చిరునామా మార్చండి",
                  "selectAddress" to "క్రింద సరైన చిరునామాను నొక్కండి.",
                  "openAppSettings" to "యాప్ అనుమతులు తెరవండి",
                  "storeUnavailable" to "మీ ఫోన్‌లో Play Store తెరిచి Uber కోసం వెతకండి.",
                  "rideInterrupted" to "రైడ్ అభ్యర్థన ఆగిపోయింది. గమ్యస్థానాన్ని చూసి మళ్లీ ప్రయత్నించండి.",
                  "addressSearchHint" to "స్వయంచాలకంగా వెతకడానికి కనీసం 3 అక్షరాలు టైప్ చేయండి.",
                  "searchPending" to "టైప్ చేయడం ఆపినప్పుడు వెతుకులాట మొదలవుతుంది…",
                  "searchingAddress" to "చిరునామాలను వెతుకుతున్నాం…",
                  "sharedLocation" to "షేర్ చేసిన లొకేషన్",
                  "invalidSharedLocation" to "ఈ సందేశంలో మద్దతు ఉన్న లొకేషన్ లేదు. Ride Saathiతో లొకేషన్ లేదా Google Maps లింక్ షేర్ చేయండి.",
                  "sharedLocationSetup" to "షేర్ చేసిన లొకేషన్ వాడే ముందు Ride Saathi సెటప్ పూర్తి చేయండి.",
                  "resolvingSharedLocation" to "షేర్ చేసిన లొకేషన్ తెరుస్తున్నాం…",
                  "selectSharedLocation" to "షేర్ చేసిన గమ్యస్థానాన్ని ఎంచుకోండి",
                  "sharedSearchHint" to "లింక్‌లో చిరునామా ఉంది. ఈ శోధన ఫలితాలను చూసి సరైన స్థలాన్ని ఎంచుకోండి.",
                  "sharedLocationOffline" to "Google Maps లింక్ తెరవలేకపోయాం. ఇంటర్నెట్ కనెక్షన్ చూసి మళ్లీ షేర్ చేయండి.",
                  "sharedLocationUnresolved" to "ఆ లింక్‌లో గమ్యస్థానం పిన్ దొరకలేదు. Google Mapsలో స్థలాన్ని ఎంచుకోండి లేదా పిన్ పెట్టి మళ్లీ షేర్ చేయండి.",
                  "hello" to "నమస్కారం",
                  "setupHint" to "సులభమైన ప్రయాణాల కోసం చిన్న సెటప్. కుటుంబ సభ్యులు సహాయం చేయవచ్చు.",
                  "voiceHint" to "మీరు ఎక్కడికి వెళ్లాలనుకుంటున్నారో చెప్పండి.",
                  "tapHint" to "లేదా ప్రారంభించడానికి క్రింద ఒక స్థలాన్ని నొక్కండి.",
                  "handoffHint" to "మీ రైడ్ ఎంచుకుని Uberలో బుకింగ్ పూర్తి చేయండి.",
                  "welcome" to "రైడ్ సాథికి స్వాగతం",
                  "language" to "మీ భాషను ఎంచుకోండి",
                  "name" to "మీ పేరు",
                  "continue" to "కొనసాగించు",
                  "homeRequired" to "ముందుకు వెళ్లడానికి ఇల్లు జోడించండి",
                  "home" to "ఇల్లు",
                  "addHome" to "ఇల్లు జోడించు",
                  "addPlace" to "మరో స్థలం జోడించు",
                  "finish" to "సెటప్ పూర్తి చేయి",
                  "uberInstall" to "రైడ్ కోసం Uber ఇన్‌స్టాల్ చేయండి",
                  "install" to "Play Store తెరువు",
                  "places" to "సేవ్ చేసిన స్థలాలు",
                  "settings" to "సెట్టింగ్‌లు",
                  "rideTo" to "మీరు ఎక్కడికి వెళ్లాలి?",
                  "speak" to "మాట్లాడండి",
                  "listening" to "వింటున్నాం…",
                  "recognizedSpeech" to "యాప్ విన్న మాటలు",
                  "heardSoFar" to "ఇప్పటివరకు విన్నది…",
                  "cancel" to "రద్దు",
                  "confirm" to "ఇదే మీ గమ్యస్థానమా?",
                  "yes" to "అవును, Uber తెరువు",
                  "no" to "కాదు, మళ్లీ ఎంచుకోండి",
                  "working" to "మీ ప్రస్తుత స్థానం చూస్తున్నాం…",
                  "locationDenied" to "పికప్ కోసం లొకేషన్ అనుమతి ఇవ్వండి.",
                  "locationUnavailable" to
                          "మీ ప్రస్తుత స్థానం దొరకలేదు. లొకేషన్ చూసి మళ్లీ ప్రయత్నించండి.",
                  "retry" to "మళ్లీ ప్రయత్నించు",
                  "unknown" to "ఆ స్థలం సేవ్ చేయలేదు. క్రింద ఎంచుకోండి.",
                  "ambiguous" to "ఏ స్థలానికి వెళ్లాలి?",
                  "speechFailed" to "వినిపించలేదు. మళ్లీ చెప్పండి లేదా స్థలం నొక్కండి.",
                  "micDenied" to "మాట్లాడడానికి మైక్రోఫోన్ అనుమతి ఇవ్వండి, లేదా స్థలం నొక్కండి.",
                  "placeName" to "స్థలం పేరు",
                  "search" to "చిరునామా వెతుకు",
                  "address" to "చిరునామా",
                  "save" to "స్థలం సేవ్ చేయి",
                  "delete" to "స్థలం తొలగించు",
                  "duplicate" to "ఈ పేరు ఇప్పటికే ఉంది.",
                  "invalidPlace" to "ముందు వెతికి చిరునామా ఎంచుకోండి.",
                  "replaceHome" to "ఇల్లు తొలగించే ముందు కొత్త ఇల్లు జోడించండి.",
                  "edit" to "మార్చు",
                  "done" to "పూర్తయింది",
                  "handoffFailed" to "Uber తెరుచుకోలేదు. మళ్లీ ప్రయత్నించండి.",
                  "offline" to "వెతకడానికి ఇంటర్నెట్ కావాలి. తర్వాత ప్రయత్నించండి.",
                  "changeLanguage" to "భాష",
                  "manage" to "స్థలాలు మార్చు",
                  "back" to "వెనక్కి",
                  "configured" to "చిరునామా వెతుకులాట ఇంకా సిద్ధంగా లేదు.",
                  "choosePlace" to "సేవ్ చేసిన స్థలం ఎంచుకోండి",
                  "stop" to "వినడం ఆపు",
                  "wait" to "దయచేసి వేచి ఉండండి",
                  "voiceUnavailable" to "వాయిస్ సేవ లేదు. స్థలం నొక్కండి.",
                  "openLocation" to "లొకేషన్ సెట్టింగ్‌లు తెరువు",
                  "noResults" to "దగ్గరలో చిరునామా దొరకలేదు. దగ్గరలోని స్థలం లేదా ప్రాంతం పేరుతో మళ్లీ వెతకండి.",
                  "mapAttribution" to "మ్యాప్ డేటా © OpenStreetMap సహకారులు",
                  "providerSettings" to "కుటుంబ సెటప్: మ్యాప్ సేవలు",
                  "searchService" to "చిరునామా శోధన సేవ URL",
                  "mapService" to "మ్యాప్ సేవ URL",
                  "invalidService" to "చెల్లుబాటు అయ్యే HTTPS సేవ URL ఇవ్వండి.",
                  "saveServices" to "సేవ URLలను సేవ్ చేయి",
                  "servicesSaved" to "సేవ URLలు సేవ్ అయ్యాయి.",
                  "mapUnavailable" to "మ్యాప్ లోడ్ కాలేదు. ఇంటర్నెట్ చూసి మళ్లీ ప్రయత్నించండి.",
                  "showMore" to "మరింత చూడండి",
                  "showLess" to "తక్కువగా చూడండి",
                  "watchIntro" to "Ride Saathi ఎలా సహాయం చేస్తుంది",
                  "watchTutorial" to "ట్యుటోరియల్ చూడండి",
                  "introTitle" to "సెటప్‌కు ముందు",
                  "tutorialTitle" to "రైడ్ ఎలా అడగాలి",
                  "introFamilyTitle" to "కుటుంబం ఒకసారి సెటప్ చేస్తుంది",
                  "introFamilyBody" to "కుటుంబ సభ్యులు మీ ఇల్లు మరియు మీరు తరచుగా వెళ్లే స్థలాలను జోడించవచ్చు.",
                  "introPlacesTitle" to "తర్వాత రైడ్‌లు సులభం",
                  "introPlacesBody" to "సెటప్ తర్వాత, ప్రారంభించడానికి స్థలం చెప్పండి లేదా నొక్కండి.",
                  "tutorialSpeakTitle" to "స్థలం చెప్పండి లేదా నొక్కండి",
                  "tutorialSpeakBody" to "Doctor లాంటి సేవ్ చేసిన స్థలం చెప్పండి, లేదా స్క్రీన్‌పై స్థలం పేరును నొక్కండి.",
                  "tutorialConfirmTitle" to "గమ్యస్థానం చూసుకోండి",
                  "tutorialConfirmBody" to "ముందుకు వెళ్లే ముందు Ride Saathi మీతో స్థలాన్ని నిర్ధారించుకుంటుంది.",
                  "tutorialPickupTitle" to "పికప్ మీ ప్రస్తుత స్థానం",
                  "tutorialPickupBody" to "పికప్ నింపడానికి Ride Saathi మీ ఫోన్ లొకేషన్ మాత్రమే ఉపయోగిస్తుంది.",
                  "tutorialUberTitle" to "Uberలో పూర్తి చేయండి",
                  "tutorialUberBody" to "Uber గమ్యస్థానంతో తెరుచుకుంటుంది. రైడ్ ఎంచుకుని Uberలో బుక్ చేయండి.",
                  "replayAudio" to "మళ్లీ వినండి",
                  "skipTutorial" to "దాటవేయి",
                  "continueSetup" to "సెటప్ కొనసాగించు",
                  "startUsing" to "Ride Saathi ప్రారంభించు"
          )

  fun get(language: String, key: String): String =
          when (language) {
            "hi" -> hi[key]
            "te" -> te[key]
            else -> en[key]
          }
                  ?: en[key] ?: key
}
