package com.ridesaathi.app.localization

internal val hi = mapOf(
    "interruptSpeak" to "बीच में रोककर बोलें",
    "bargeInHint" to "आप बोलकर बीच में रोक सकते हैं",
    "tapInterruptHint" to "बीच में रोकने के लिए माइक्रोफ़ोन दबाएँ",

    "goodMorning" to "सुप्रभात",
    "goodAfternoon" to "नमस्कार",
    "goodEvening" to "शुभ संध्या",
    "enterFullAddress" to "अपना पूरा पता लिखें",
    "typeManually" to "पता लिखें",
    "searchSavedPlaces" to "सहेजी गई जगहें खोजें",
    "addPlaceHint" to "जल्दी बुकिंग के लिए जगह सहेजें",
    "clear" to "लिखा हुआ हटाएँ",
    "manualDestination" to "कोई दूसरी जगह दर्ज करें",
    "quickPlaces" to "आपकी जगहें",
    "seeAll" to "सभी देखें",
    "bookRide" to "राइड बुक करें",
    "tapSpeak" to "टैप करें और बोलें",
    "getStarted" to "शुरू करें",
    "savedPlacesHint" to "आसान सफ़र के लिए अपनी जगहें सहेजें।",

    "onboardingStep" to "चरण {current} / {total}",
    "onboardingLanguageHint" to "जिस भाषा में आप सहज हैं, उसे चुनें।",
    "onboardingNameTitle" to "हम आपको किस नाम से बुलाएँ?",
    "onboardingNameHint" to "कृपया अपना नाम बताएँ। आपके अनुभव को व्यक्तिगत बनाने और आगे बढ़ने के लिए यह ज़रूरी है।",
    "onboardingHomeTitle" to "अपना घर सहेजें",
    "onboardingHomeHint" to "घर का पता एक बार सेव करें, ताकि वापस जाने के लिए उसे आसानी से चुन सकें।",
    "onboardingHomeSearch" to "अपने घर का पता खोजें और सेव करने से पहले नक्शे पर पिन जाँचें।",
    "onboardingHomeSaved" to "घर सेव हो गया है। बदलाव करने के लिए नीचे टैप करें।",
    "onboardingPlacesTitle" to "आपकी रोज़मर्रा की जगहें",
    "onboardingPlacesHint" to "डॉक्टर, परिवार या कोई पसंदीदा जगह जोड़ें। यह ज़रूरी नहीं है — आप बाद में सेटिंग्स से भी जोड़ सकते हैं।",

    "searchDestinations" to "अपनी मंज़िल चुनें",
    "searchQuery" to "जगह का नाम और इलाका",
    "searchingDestination" to "जगह खोज रहे हैं…",
    "searchLocationRequired" to "आस-पास की जगहें खोजने के लिए आपकी अभी की लोकेशन चाहिए। लोकेशन की अनुमति दें, लोकेशन चालू करें और फिर कोशिश करें।",
    "searchChoose" to "आप कौन सी जगह जाना चाहते हैं?",
    "searchChoiceHint" to "एक, दो या तीन बोलें, या जगह पर टैप करें। जगह बदलने के लिए “फिर खोजें” बोलें।",
    "searchMoreHint" to "बाकी जगहों के लिए “और नतीजे” बोलें।",
    "searchMore" to "और नतीजे",
    "searchPrevious" to "पिछले नतीजे",
    "searchAgain" to "फिर खोजें",
    "searchRepeat" to "फिर सुनाएँ",
    "searchNoMore" to "और नतीजे नहीं हैं। दूसरे नाम या इलाके के लिए “फिर खोजें” बोलें।",
    "searchClearer" to "जगह का नाम और उसका इलाका या शहर बोलें या लिखें।",
    "searchChoiceUnclear" to "इन जगहों में से किसी एक का नंबर बोलें, या उस पर टैप करें।",
    "searchNoResults" to "आस-पास कोई जगह नहीं मिली। आस-पास की जगह या इलाके के नाम से फिर खोजें।",
    "searchInterrupted" to "खोज रुक गई है। जारी रखने के लिए फिर कोशिश करें।",
    "searchAttribution" to "पते की खोज: Ola Maps",
    "searchAccessDenied" to "Ola Maps से संपर्क नहीं हो सका। ऐप इंस्टॉल करने वाले व्यक्ति से मदद लें।",
    "searchQuota" to "पते की खोज की उपयोग सीमा पूरी हो गई है। बाद में फिर कोशिश करें।",
    "searchUnavailable" to "पते की खोज अभी उपलब्ध नहीं है। फिर कोशिश करें।",
    "hello" to "नमस्ते",
    "setupHint" to "आसान सफ़र के लिए छोटा सा सेटअप। परिवार का कोई सदस्य मदद कर सकता है।",
    "voiceHint" to "जहाँ जाना है उस जगह का नाम बोलें।",
    "tapHint" to "या शुरू करने के लिए नीचे कोई जगह चुनें।",
    "handoffHint" to "अपनी सवारी चुनें और बुकिंग Uber में पूरी करें।",
    "welcome" to "राइड साथी में आपका स्वागत है",
    "language" to "अपनी भाषा चुनें",
    "name" to "आपका नाम",
    "continue" to "आगे बढ़ें",
    "homeRequired" to "आगे बढ़ने के लिए घर जोड़ें",
    "home" to "घर",
    "addHome" to "घर जोड़ें",
    "addPlace" to "एक और जगह जोड़ें",
    "finish" to "सेटअप पूरा करें",
    "uberInstall" to "यात्रा के लिए Uber इंस्टॉल करें",
    "install" to "Play Store खोलें",
    "places" to "चुनी गई जगहें",
    "settings" to "सेटिंग्स",
    "rideTo" to "आप कहाँ जाना चाहते हैं?",
    "speak" to "बोलें",
    "listening" to "सुन रहे हैं…",
    "recognizedSpeech" to "ऐप ने यह सुना",
    "heardSoFar" to "अब तक सुना…",
    "cancel" to "रद्द करें",
    "confirm" to "क्या यही आपकी मंज़िल है?",
    "yes" to "हाँ, Uber खोलें",
    "no" to "नहीं, फिर चुनें",
    "working" to "आपकी अभी की लोकेशन ढूँढ रहे हैं…",
    "locationDenied" to "पिकअप के लिए आपकी अभी की लोकेशन चाहिए। इसकी अनुमति दें।",
    "locationUnavailable" to
            "आपकी अभी की लोकेशन नहीं मिली। लोकेशन चेक करें और फिर कोशिश करें।",
    "retry" to "फिर कोशिश करें",
    "unknown" to "यह जगह चुनी हुई जगहों में नहीं है। नीचे से चुनें।",
    "ambiguous" to "आप किस जगह जाना चाहते हैं?",
    "speechFailed" to "आवाज़ समझ नहीं आई। फिर बोलें या जगह चुनें।",
    "micDenied" to "बोलने के लिए माइक्रोफ़ोन की अनुमति दें, या नीचे से जगह चुनें।",
    "placeName" to "जगह का नाम",
    "placeNameHint" to "वह नाम लिखें जो आप सवारी माँगते समय बोलेंगे।",
    "editPlace" to "जगह बदलें",
    "changeAddress" to "पता बदलें",
    "selectAddress" to "नीचे सही पते पर टैप करें।",
    "openAppSettings" to "ऐप की अनुमतियाँ खोलें",
    "storeUnavailable" to "अपने फ़ोन पर Play Store खोलें और Uber खोजें।",
    "rideInterrupted" to "यात्रा का अनुरोध रुक गया। जगह जाँचें और फिर कोशिश करें।",
    "search" to "पता खोजें",
    "addressSearchHint" to "अपने आप खोजने के लिए कम से कम 3 अक्षर लिखें।",
    "searchPending" to "आपके लिखना रोकने पर खोज शुरू होगी…",
    "searchingAddress" to "पते खोज रहे हैं…",
    "address" to "पता",
    "save" to "जगह सेव करें",
    "delete" to "जगह हटाएँ",
    "duplicate" to "यह नाम पहले से है।",
    "invalidPlace" to "पहले खोज में से कोई पता चुनें।",
    "replaceHome" to "घर हटाने से पहले नया घर जोड़ें।",
    "edit" to "बदलें",
    "done" to "हो गया",
    "handoffFailed" to "Uber नहीं खुला। फिर कोशिश करें।",
    "offline" to "खोज के लिए इंटरनेट चाहिए। बाद में कोशिश करें।",
    "changeLanguage" to "भाषा",
    "manage" to "जगहें बदलें",
    "back" to "वापस",
    "configured" to "पता खोज अभी सेट नहीं है।",
    "choosePlace" to "चुनी गई जगह चुनें",
    "stop" to "सुनना बंद करें",
    "wait" to "कृपया प्रतीक्षा करें",
    "voiceUnavailable" to "आवाज़ की सुविधा नहीं चल रही। नीचे से जगह चुनें।",
    "openLocation" to "लोकेशन सेटिंग्स खोलें",
    "noResults" to "आस-पास पता नहीं मिला। आस-पास की जगह या इलाके के नाम से फिर खोजें।",
    "mapAttribution" to "नक्शे का डेटा © OpenStreetMap योगदानकर्ता",
    "providerSettings" to "परिवार सेटअप: नक्शा सेवाएँ",
    "searchService" to "पता खोज सेवा URL",
    "mapService" to "नक्शा सेवा URL",
    "invalidService" to "मान्य HTTPS सेवा URL डालें।",
    "saveServices" to "सेवा URL सेव करें",
    "servicesSaved" to "सेवा URL सेव हो गए।",
    "mapUnavailable" to "नक्शा नहीं खुला। इंटरनेट चेक करें और फिर कोशिश करें।",
    "showMore" to "और देखें",
    "showLess" to "कम देखें",
    "sharedLocation" to "शेयर की गई लोकेशन",
    "invalidSharedLocation" to "इस संदेश में लोकेशन नहीं मिली। Ride Saathi के साथ लोकेशन या Google Maps लिंक शेयर करें।",
    "sharedLocationSetup" to "शेयर की गई लोकेशन इस्तेमाल करने से पहले Ride Saathi का सेटअप पूरा करें।",
    "resolvingSharedLocation" to "शेयर की गई लोकेशन खोली जा रही है…",
    "selectSharedLocation" to "शेयर की गई मंज़िल चुनें",
    "sharedSearchHint" to "लिंक में पता मिला है। खोज के नतीजे जाँचें और सही जगह चुनें।",
    "sharedLocationOffline" to "Google Maps लिंक नहीं खुल सका। इंटरनेट कनेक्शन जाँचें और फिर से शेयर करें।",
    "sharedLocationUnresolved" to "इस लिंक में मंज़िल का पिन नहीं मिला। Google Maps में कोई जगह चुनें या पिन लगाएँ, फिर से शेयर करें।",
    "watchIntro" to "Ride Saathi कैसे मदद करता है",
    "watchTutorial" to "ट्यूटोरियल देखें",
    "introTitle" to "सेटअप से पहले",
    "tutorialTitle" to "राइड कैसे माँगें",
    "introAboutTitle" to "बस बोलकर अपनी मंज़िल तक पहुँचें",
    "introAboutBody" to "अपनी भाषा में आसानी से Uber बुक करें।",
    "introFamilyTitle" to "परिवार एक बार सेटअप करता है",
    "introFamilyBody" to "परिवार का कोई सदस्य आपका घर और रोज़ जाने वाली जगहें जोड़ सकता है।",
    "introPlacesTitle" to "फिर राइड आसान हो जाती है",
    "introPlacesBody" to "सेटअप के बाद, शुरू करने के लिए जगह बोलें या उस पर टैप करें।",
    "tutorialSpeakTitle" to "जगह बोलें या टैप करें",
    "tutorialSpeakBody" to "Doctor जैसी सेव की हुई जगह बोलें, या स्क्रीन पर जगह का नाम टैप करें।",
    "tutorialConfirmTitle" to "मंज़िल जाँचें",
    "tutorialConfirmBody" to "Ride Saathi आगे बढ़ने से पहले आपसे जगह कन्फर्म करवाता है।",
    "tutorialPickupTitle" to "पिकअप आपकी अभी की लोकेशन है",
    "tutorialPickupBody" to "Ride Saathi पिकअप भरने के लिए सिर्फ़ आपके फ़ोन की लोकेशन इस्तेमाल करता है।",
    "tutorialUberTitle" to "Uber में पूरा करें",
    "tutorialUberBody" to "Uber मंज़िल के साथ खुलता है। राइड चुनें और बुकिंग Uber में करें।",
    "replayAudio" to "फिर सुनें",
    "skipTutorial" to "छोड़ें",
    "continueSetup" to "सेटअप जारी रखें",
    "startUsing" to "Ride Saathi शुरू करें"
)
