package com.ridesaathi.app.localization

internal val te = mapOf(
    "interruptSpeak" to "మధ్యలో ఆపి మాట్లాడండి",
    "bargeInHint" to "మధ్యలో ఆపడానికి మాట్లాడండి",
    "tapInterruptHint" to "మధ్యలో ఆపడానికి మైక్రోఫోన్ నొక్కండి",

    "goodMorning" to "శుభోదయం",
    "goodAfternoon" to "శుభ మధ్యాహ్నం",
    "goodEvening" to "శుభ సాయంత్రం",
    "enterFullAddress" to "మీ పూర్తి చిరునామాను నమోదు చేయండి",
    "typeManually" to "చిరునామా టైప్ చేయండి",
    "searchSavedPlaces" to "సేవ్ చేసిన ప్రదేశాలను వెతకండి",
    "addPlaceHint" to "త్వరగా బుక్ చేయడానికి ప్రదేశాన్ని సేవ్ చేయండి",
    "clear" to "వచనాన్ని తొలగించండి",
    "manualDestination" to "వేరే గమ్యస్థానాన్ని నమోదు చేయండి",
    "quickPlaces" to "మీ ప్రదేశాలు",
    "seeAll" to "అన్నీ చూడండి",
    "bookRide" to "రైడ్ బుక్ చేయండి",
    "tapSpeak" to "నొక్కి మాట్లాడండి",
    "getStarted" to "ప్రారంభించండి",
    "savedPlacesHint" to "సులభమైన ప్రయాణాల కోసం మీ ప్రదేశాలను సేవ్ చేయండి।",

    "onboardingStep" to "దశ {current} / {total}",
    "onboardingLanguageHint" to "మీకు సౌకర్యంగా ఉన్న భాషను ఎంచుకోండి.",
    "onboardingNameTitle" to "మిమ్మల్ని ఏమని పిలవాలి?",
    "onboardingNameHint" to "దయచేసి మీ పేరు నమోదు చేయండి. మీకు అనుగుణమైన అనుభవం కోసం, కొనసాగడానికి ఇది అవసరం.",
    "onboardingHomeTitle" to "మీ ఇంటిని సేవ్ చేయండి",
    "onboardingHomeHint" to "మీ ఇంటి చిరునామాను ఒకసారి సేవ్ చేస్తే, తిరిగి వెళ్లడానికి సులభంగా ఎంచుకోవచ్చు.",
    "onboardingHomeSearch" to "మీ ఇంటి చిరునామాను వెతికి, సేవ్ చేసే ముందు మ్యాప్‌లో పిన్‌ను సరిచూసుకోండి.",
    "onboardingHomeSaved" to "ఇల్లు సేవ్ అయింది. మార్చడానికి కింద నొక్కండి.",
    "onboardingPlacesTitle" to "మీరు తరచూ వెళ్లే ప్రదేశాలు",
    "onboardingPlacesHint" to "డాక్టర్, కుటుంబం లేదా ఇష్టమైన ప్రదేశాన్ని జోడించండి. ఇది ఐచ్ఛికం — తర్వాత సెట్టింగ్స్‌లో కూడా జోడించవచ్చు.",

    "searchDestinations" to "మీ గమ్యస్థానాన్ని ఎంచుకోండి",
    "searchQuery" to "స్థలం పేరు మరియు ప్రాంతం",
    "searchingDestination" to "స్థలాలను వెతుకుతున్నాం…",
    "searchLocationRequired" to "దగ్గరలోని స్థలాలను వెతకడానికి మీ ప్రస్తుత స్థానం కావాలి. లొకేషన్ అనుమతి ఇచ్చి, లొకేషన్ ఆన్ చేసి మళ్లీ ప్రయత్నించండి.",
    "searchChoose" to "మీరు ఏ స్థలానికి వెళ్లాలనుకుంటున్నారు?",
    "searchChoiceHint" to "ఒకటి, రెండు లేదా మూడు చెప్పండి, లేదా స్థలాన్ని నొక్కండి. స్థలం మార్చడానికి “మళ్లీ వెతకండి” అని చెప్పండి.",
    "searchMoreHint" to "ఇతర స్థలాల కోసం “మరిన్ని ఫలితాలు” అని చెప్పండి.",
    "searchMore" to "మరిన్ని ఫలితాలు",
    "searchPrevious" to "మునుపటి ఫలితాలు",
    "searchAgain" to "మళ్లీ వెతకండి",
    "searchRepeat" to "మళ్లీ వినిపించండి",
    "searchNoMore" to "ఇంకా ఫలితాలు లేవు. వేరే పేరు లేదా ప్రాంతంతో ప్రయత్నించడానికి “మళ్లీ వెతకండి” అని చెప్పండి.",
    "searchClearer" to "స్థలం పేరు, దాని ప్రాంతం లేదా నగరం చెప్పండి లేదా టైప్ చేయండి.",
    "searchChoiceUnclear" to "ఈ స్థలాల్లో ఒకదాని సంఖ్య చెప్పండి, లేదా దాన్ని నొక్కండి.",
    "searchNoResults" to "దగ్గరలో సరిపోయే స్థలాలు దొరకలేదు. దగ్గరలోని స్థలం లేదా ప్రాంతం పేరుతో మళ్లీ వెతకండి.",
    "searchInterrupted" to "వెతుకులాట ఆగిపోయింది. కొనసాగించడానికి మళ్లీ ప్రయత్నించండి.",
    "searchAttribution" to "చిరునామా శోధన: Ola Maps",
    "searchAccessDenied" to "Ola Mapsతో కనెక్ట్ కాలేదు. యాప్ ఇన్‌స్టాల్ చేసిన వ్యక్తి సహాయం తీసుకోండి.",
    "searchQuota" to "చిరునామా శోధన వినియోగ పరిమితి చేరుకుంది. తర్వాత మళ్లీ ప్రయత్నించండి.",
    "searchUnavailable" to "చిరునామా శోధన ప్రస్తుతం అందుబాటులో లేదు. మళ్లీ ప్రయత్నించండి.",
    "placeNameHint" to "రైడ్ అడిగేటప్పుడు మీరు చెప్పే పేరును వాడండి.",
    "editPlace" to "స్థలాన్ని మార్చండి",
    "changeAddress" to "చిరునామా మార్చండి",
    "selectAddress" to "క్రింద సరైన చిరునామాను నొక్కండి.",
    "openAppSettings" to "యాప్ అనుమతులు తెరవండి",
    "storeUnavailable" to "మీ ఫోన్‌లో Play Store తెరిచి Uber కోసం వెతకండి.",
    "rideInterrupted" to "రైడ్ అభ్యర్థన ఆగిపోయింది. గమ్యస్థానాన్ని చూసి మళ్లీ ప్రయత్నించండి.",
    "addressSearchHint" to "స్వయంచాలకంగా వెతకడానికి కనీసం 3 అక్షరాలు టైప్ చేయండి.",
    "searchPending" to "టైప్ చేయడం ఆపినప్పుడు వెతుకులాట మొదలవుతుంది…",
    "searchingAddress" to "చిరునామాలను వెతుకుతున్నాం…",
    "sharedLocation" to "షేర్ చేసిన లొకేషన్",
    "invalidSharedLocation" to "ఈ సందేశంలో మద్దతు ఉన్న లొకేషన్ లేదు. Ride Saathiతో లొకేషన్ లేదా Google Maps లింక్ షేర్ చేయండి.",
    "sharedLocationSetup" to "షేర్ చేసిన లొకేషన్ వాడే ముందు Ride Saathi సెటప్ పూర్తి చేయండి.",
    "resolvingSharedLocation" to "షేర్ చేసిన లొకేషన్ తెరుస్తున్నాం…",
    "selectSharedLocation" to "షేర్ చేసిన గమ్యస్థానాన్ని ఎంచుకోండి",
    "sharedSearchHint" to "లింక్‌లో చిరునామా ఉంది. ఈ శోధన ఫలితాలను చూసి సరైన స్థలాన్ని ఎంచుకోండి.",
    "sharedLocationOffline" to "Google Maps లింక్ తెరవలేకపోయాం. ఇంటర్నెట్ కనెక్షన్ చూసి మళ్లీ షేర్ చేయండి.",
    "sharedLocationUnresolved" to "ఆ లింక్‌లో గమ్యస్థానం పిన్ దొరకలేదు. Google Mapsలో స్థలాన్ని ఎంచుకోండి లేదా పిన్ పెట్టి మళ్లీ షేర్ చేయండి.",
    "hello" to "నమస్కారం",
    "setupHint" to "సులభమైన ప్రయాణాల కోసం చిన్న సెటప్. కుటుంబ సభ్యులు సహాయం చేయవచ్చు.",
    "voiceHint" to "మీరు ఎక్కడికి వెళ్లాలనుకుంటున్నారో చెప్పండి.",
    "tapHint" to "లేదా ప్రారంభించడానికి క్రింద ఒక స్థలాన్ని నొక్కండి.",
    "handoffHint" to "మీ రైడ్ ఎంచుకుని Uberలో బుకింగ్ పూర్తి చేయండి.",
    "welcome" to "రైడ్ సాథికి స్వాగతం",
    "language" to "మీ భాషను ఎంచుకోండి",
    "name" to "మీ పేరు",
    "continue" to "కొనసాగించు",
    "homeRequired" to "ముందుకు వెళ్లడానికి ఇల్లు జోడించండి",
    "home" to "ఇల్లు",
    "addHome" to "ఇల్లు జోడించు",
    "addPlace" to "మరో స్థలం జోడించు",
    "finish" to "సెటప్ పూర్తి చేయి",
    "uberInstall" to "రైడ్ కోసం Uber ఇన్‌స్టాల్ చేయండి",
    "install" to "Play Store తెరువు",
    "places" to "సేవ్ చేసిన స్థలాలు",
    "settings" to "సెట్టింగ్‌లు",
    "rideTo" to "మీరు ఎక్కడికి వెళ్లాలి?",
    "speak" to "మాట్లాడండి",
    "listening" to "వింటున్నాం…",
    "recognizedSpeech" to "యాప్ విన్న మాటలు",
    "heardSoFar" to "ఇప్పటివరకు విన్నది…",
    "cancel" to "రద్దు",
    "confirm" to "ఇదే మీ గమ్యస్థానమా?",
    "yes" to "అవును, Uber తెరువు",
    "no" to "కాదు, మళ్లీ ఎంచుకోండి",
    "working" to "మీ ప్రస్తుత స్థానం చూస్తున్నాం…",
    "locationDenied" to "పికప్ కోసం లొకేషన్ అనుమతి ఇవ్వండి.",
    "locationUnavailable" to
            "మీ ప్రస్తుత స్థానం దొరకలేదు. లొకేషన్ చూసి మళ్లీ ప్రయత్నించండి.",
    "retry" to "మళ్లీ ప్రయత్నించు",
    "unknown" to "ఆ స్థలం సేవ్ చేయలేదు. క్రింద ఎంచుకోండి.",
    "ambiguous" to "ఏ స్థలానికి వెళ్లాలి?",
    "speechFailed" to "వినిపించలేదు. మళ్లీ చెప్పండి లేదా స్థలం నొక్కండి.",
    "micDenied" to "మాట్లాడడానికి మైక్రోఫోన్ అనుమతి ఇవ్వండి, లేదా స్థలం నొక్కండి.",
    "placeName" to "స్థలం పేరు",
    "search" to "చిరునామా వెతుకు",
    "address" to "చిరునామా",
    "save" to "స్థలం సేవ్ చేయి",
    "delete" to "స్థలం తొలగించు",
    "duplicate" to "ఈ పేరు ఇప్పటికే ఉంది.",
    "invalidPlace" to "ముందు వెతికి చిరునామా ఎంచుకోండి.",
    "replaceHome" to "ఇల్లు తొలగించే ముందు కొత్త ఇల్లు జోడించండి.",
    "edit" to "మార్చు",
    "done" to "పూర్తయింది",
    "handoffFailed" to "Uber తెరుచుకోలేదు. మళ్లీ ప్రయత్నించండి.",
    "offline" to "వెతకడానికి ఇంటర్నెట్ కావాలి. తర్వాత ప్రయత్నించండి.",
    "changeLanguage" to "భాష",
    "manage" to "స్థలాలు మార్చు",
    "back" to "వెనక్కి",
    "configured" to "చిరునామా వెతుకులాట ఇంకా సిద్ధంగా లేదు.",
    "choosePlace" to "సేవ్ చేసిన స్థలం ఎంచుకోండి",
    "stop" to "వినడం ఆపు",
    "wait" to "దయచేసి వేచి ఉండండి",
    "voiceUnavailable" to "వాయిస్ సేవ లేదు. స్థలం నొక్కండి.",
    "openLocation" to "లొకేషన్ సెట్టింగ్‌లు తెరువు",
    "noResults" to "దగ్గరలో చిరునామా దొరకలేదు. దగ్గరలోని స్థలం లేదా ప్రాంతం పేరుతో మళ్లీ వెతకండి.",
    "mapAttribution" to "మ్యాప్ డేటా © OpenStreetMap సహకారులు",
    "providerSettings" to "కుటుంబ సెటప్: మ్యాప్ సేవలు",
    "searchService" to "చిరునామా శోధన సేవ URL",
    "mapService" to "మ్యాప్ సేవ URL",
    "invalidService" to "చెల్లుబాటు అయ్యే HTTPS సేవ URL ఇవ్వండి.",
    "saveServices" to "సేవ URLలను సేవ్ చేయి",
    "servicesSaved" to "సేవ URLలు సేవ్ అయ్యాయి.",
    "mapUnavailable" to "మ్యాప్ లోడ్ కాలేదు. ఇంటర్నెట్ చూసి మళ్లీ ప్రయత్నించండి.",
    "showMore" to "మరింత చూడండి",
    "showLess" to "తక్కువగా చూడండి",
    "watchIntro" to "Ride Saathi ఎలా సహాయం చేస్తుంది",
    "watchTutorial" to "ట్యుటోరియల్ చూడండి",
    "introTitle" to "సెటప్‌కు ముందు",
    "tutorialTitle" to "రైడ్ ఎలా అడగాలి",
    "introAboutTitle" to "మీ మాటతోనే గమ్యానికి చేరుకోండి",
    "introAboutBody" to "మీ భాషలో సులభంగా Uber బుక్ చేయండి.",
    "introFamilyTitle" to "కుటుంబం ఒకసారి సెటప్ చేస్తుంది",
    "introFamilyBody" to "కుటుంబ సభ్యులు మీ ఇల్లు మరియు మీరు తరచుగా వెళ్లే స్థలాలను జోడించవచ్చు.",
    "introPlacesTitle" to "తర్వాత రైడ్‌లు సులభం",
    "introPlacesBody" to "సెటప్ తర్వాత, ప్రారంభించడానికి స్థలం చెప్పండి లేదా నొక్కండి.",
    "tutorialSpeakTitle" to "స్థలం చెప్పండి లేదా నొక్కండి",
    "tutorialSpeakBody" to "Doctor లాంటి సేవ్ చేసిన స్థలం చెప్పండి, లేదా స్క్రీన్‌పై స్థలం పేరును నొక్కండి.",
    "tutorialConfirmTitle" to "గమ్యస్థానం చూసుకోండి",
    "tutorialConfirmBody" to "ముందుకు వెళ్లే ముందు Ride Saathi మీతో స్థలాన్ని నిర్ధారించుకుంటుంది.",
    "tutorialPickupTitle" to "పికప్ మీ ప్రస్తుత స్థానం",
    "tutorialPickupBody" to "పికప్ నింపడానికి Ride Saathi మీ ఫోన్ లొకేషన్ మాత్రమే ఉపయోగిస్తుంది.",
    "tutorialUberTitle" to "Uberలో పూర్తి చేయండి",
    "tutorialUberBody" to "Uber గమ్యస్థానంతో తెరుచుకుంటుంది. రైడ్ ఎంచుకుని Uberలో బుక్ చేయండి.",
    "replayAudio" to "మళ్లీ వినండి",
    "skipTutorial" to "దాటవేయి",
    "continueSetup" to "సెటప్ కొనసాగించు",
    "startUsing" to "Ride Saathi ప్రారంభించు"
)
