package com.ridesaathi.app

object Words {
  private val en =
          mapOf(
                  "hello" to "Hello",
                  "setupHint" to "A little setup, for easier journeys. A family member can help you get started.",
                  "voiceHint" to "Tell us the name of a saved place.",
                  "tapHint" to "Or tap a place below to get started.",
                  "handoffHint" to "You’ll choose your ride and complete your booking in Uber.",
                  "editorHint" to "Search for the address, then check the map before saving.",
                  "welcome" to "Welcome to Ride Saathi",
                  "language" to "Choose your language",
                  "name" to "Your name",
                  "continue" to "Continue",
                  "homeRequired" to "Add your Home to continue",
                  "home" to "Home",
                  "addHome" to "Add Home",
                  "addPlace" to "Add saved place",
                  "finish" to "Finish setup",
                  "uberInstall" to "Install Uber before requesting a ride",
                  "install" to "Open Play Store",
                  "places" to "Saved places",
                  "settings" to "Settings",
                  "rideTo" to "Where do you want to go?",
                  "speak" to "Speak a saved place",
                  "listening" to "Listening…",
                  "cancel" to "Cancel",
                  "confirm" to "Is this your destination?",
                  "yes" to "Yes, open Uber",
                  "no" to "No, choose again",
                  "working" to "Getting your current location…",
                  "locationDenied" to "Allow location to set your pickup point.",
                  "locationUnavailable" to
                          "We could not get your current location. Check Location and try again.",
                  "retry" to "Try again",
                  "unknown" to "I could not find that saved place. Choose one below.",
                  "ambiguous" to "Which saved place did you mean?",
                  "speechFailed" to "I did not catch that. Try again or tap a place.",
                  "micDenied" to "Allow microphone access to speak, or tap a place below.",
                  "placeName" to "Place name",
                  "aliases" to "Voice names (comma separated)",
                  "search" to "Search address",
                  "address" to "Address",
                  "checkMap" to "Check the pin on the map",
                  "save" to "Save place",
                  "delete" to "Delete place",
                  "duplicate" to "This name is already used.",
                  "invalidPlace" to "Choose an address from search first.",
                  "replaceHome" to "Replace Home before removing it.",
                  "edit" to "Edit",
                  "done" to "Done",
                  "demo" to "Tap a place or the microphone. Confirm it, then finish in Uber.",
                  "handoffFailed" to "Uber could not open. Try again.",
                  "offline" to "Search needs internet. Try again later.",
                  "changeLanguage" to "Language",
                  "manage" to "Manage places",
                  "back" to "Back",
                  "configured" to "Address search is not configured yet.",
                  "choosePlace" to "Choose a saved place",
                  "stop" to "Stop listening",
                  "wait" to "Please wait",
                  "voiceUnavailable" to "Voice service is unavailable. Tap a saved place.",
                  "openLocation" to "Open location settings",
                  "noResults" to "No matching address. Try a more specific search.",
                  "mapAttribution" to "Map data © OpenStreetMap contributors",
                  "providerSettings" to "Family setup: map services",
                  "searchService" to "Address search service URL",
                  "mapService" to "Map preview service URL",
                  "invalidService" to "Enter valid HTTPS service URLs.",
                  "saveServices" to "Save service URLs",
                  "servicesSaved" to "Service URLs saved.",
                  "mapUnavailable" to "The map could not load. Check your connection and try again."
          )
  private val hi =
          mapOf(
                  "hello" to "नमस्ते",
                  "setupHint" to "आसान सफ़र के लिए छोटा सा सेटअप। परिवार का कोई सदस्य मदद कर सकता है।",
                  "voiceHint" to "सहेजी गई जगह का नाम बताइए।",
                  "tapHint" to "या शुरू करने के लिए नीचे कोई जगह चुनें।",
                  "handoffHint" to "अपनी सवारी चुनकर बुकिंग Uber में पूरी करें।",
                  "editorHint" to "पता खोजें, फिर सहेजने से पहले नक्शा जाँचें।",
                  "welcome" to "राइड साथी में आपका स्वागत है",
                  "language" to "अपनी भाषा चुनें",
                  "name" to "आपका नाम",
                  "continue" to "आगे बढ़ें",
                  "homeRequired" to "आगे बढ़ने के लिए घर जोड़ें",
                  "home" to "घर",
                  "addHome" to "घर जोड़ें",
                  "addPlace" to "जगह जोड़ें",
                  "finish" to "सेटअप पूरा करें",
                  "uberInstall" to "यात्रा के लिए Uber इंस्टॉल करें",
                  "install" to "Play Store खोलें",
                  "places" to "सहेजी गई जगहें",
                  "settings" to "सेटिंग्स",
                  "rideTo" to "आप कहाँ जाना चाहते हैं?",
                  "speak" to "सहेजी गई जगह बोलें",
                  "listening" to "सुन रहे हैं…",
                  "cancel" to "रद्द करें",
                  "confirm" to "क्या यही आपकी मंज़िल है?",
                  "yes" to "हाँ, Uber खोलें",
                  "no" to "नहीं, फिर चुनें",
                  "working" to "आपकी मौजूदा जगह ढूँढ रहे हैं…",
                  "locationDenied" to "पिकअप के लिए लोकेशन की अनुमति दें।",
                  "locationUnavailable" to
                          "आपकी मौजूदा जगह नहीं मिली। लोकेशन जाँचें और फिर कोशिश करें।",
                  "retry" to "फिर कोशिश करें",
                  "unknown" to "यह जगह सहेजी नहीं है। नीचे से चुनें।",
                  "ambiguous" to "आप किस जगह जाना चाहते हैं?",
                  "speechFailed" to "आवाज़ समझ नहीं आई। फिर बोलें या जगह चुनें।",
                  "micDenied" to "बोलने के लिए माइक्रोफ़ोन की अनुमति दें, या नीचे जगह चुनें।",
                  "placeName" to "जगह का नाम",
                  "aliases" to "बोलने के नाम (कॉमा से अलग)",
                  "search" to "पता खोजें",
                  "address" to "पता",
                  "checkMap" to "नक्शे पर जगह जाँचें",
                  "save" to "जगह सहेजें",
                  "delete" to "जगह हटाएँ",
                  "duplicate" to "यह नाम पहले से है।",
                  "invalidPlace" to "पहले खोज से पता चुनें।",
                  "replaceHome" to "घर हटाने से पहले नया घर जोड़ें।",
                  "edit" to "बदलें",
                  "done" to "हो गया",
                  "demo" to "जगह या माइक्रोफ़ोन दबाएँ। पुष्टि करें, फिर Uber में बुक करें।",
                  "handoffFailed" to "Uber नहीं खुला। फिर कोशिश करें।",
                  "offline" to "खोज के लिए इंटरनेट चाहिए। बाद में कोशिश करें।",
                  "changeLanguage" to "भाषा",
                  "manage" to "जगहें बदलें",
                  "back" to "वापस",
                  "configured" to "पता खोज अभी सेट नहीं है।",
                  "choosePlace" to "सहेजी गई जगह चुनें",
                  "stop" to "सुनना बंद करें",
                  "wait" to "कृपया प्रतीक्षा करें",
                  "voiceUnavailable" to "आवाज़ सेवा उपलब्ध नहीं है। जगह दबाएँ।",
                  "openLocation" to "लोकेशन सेटिंग्स खोलें",
                  "noResults" to "पता नहीं मिला। अधिक जानकारी लिखकर खोजें।",
                  "mapAttribution" to "नक्शे का डेटा © OpenStreetMap योगदानकर्ता",
                  "providerSettings" to "परिवार सेटअप: नक्शा सेवाएँ",
                  "searchService" to "पता खोज सेवा URL",
                  "mapService" to "नक्शा सेवा URL",
                  "invalidService" to "मान्य HTTPS सेवा URL डालें।",
                  "saveServices" to "सेवा URL सहेजें",
                  "servicesSaved" to "सेवा URL सहेज दिए गए।",
                  "mapUnavailable" to "नक्शा नहीं खुला। इंटरनेट जाँचें और फिर कोशिश करें।"
          )
  private val te =
          mapOf(
                  "hello" to "నమస్కారం",
                  "setupHint" to "సులభమైన ప్రయాణాల కోసం చిన్న సెటప్. కుటుంబ సభ్యులు సహాయం చేయవచ్చు.",
                  "voiceHint" to "సేవ్ చేసిన స్థలం పేరు చెప్పండి.",
                  "tapHint" to "లేదా ప్రారంభించడానికి క్రింద ఒక స్థలాన్ని నొక్కండి.",
                  "handoffHint" to "మీ రైడ్ ఎంచుకుని Uberలో బుకింగ్ పూర్తి చేయండి.",
                  "editorHint" to "చిరునామా వెతికి, సేవ్ చేసే ముందు మ్యాప్ చూడండి.",
                  "welcome" to "రైడ్ సాథికి స్వాగతం",
                  "language" to "మీ భాషను ఎంచుకోండి",
                  "name" to "మీ పేరు",
                  "continue" to "కొనసాగించు",
                  "homeRequired" to "ముందుకు వెళ్లడానికి ఇల్లు జోడించండి",
                  "home" to "ఇల్లు",
                  "addHome" to "ఇల్లు జోడించు",
                  "addPlace" to "స్థలం జోడించు",
                  "finish" to "సెటప్ పూర్తి చేయి",
                  "uberInstall" to "రైడ్ కోసం Uber ఇన్‌స్టాల్ చేయండి",
                  "install" to "Play Store తెరువు",
                  "places" to "సేవ్ చేసిన స్థలాలు",
                  "settings" to "సెట్టింగ్‌లు",
                  "rideTo" to "మీరు ఎక్కడికి వెళ్లాలి?",
                  "speak" to "సేవ్ చేసిన స్థలాన్ని చెప్పండి",
                  "listening" to "వింటున్నాం…",
                  "cancel" to "రద్దు",
                  "confirm" to "ఇదే మీ గమ్యస్థానమా?",
                  "yes" to "అవును, Uber తెరువు",
                  "no" to "కాదు, మళ్లీ ఎంచుకోండి",
                  "working" to "మీ ప్రస్తుత స్థానం చూస్తున్నాం…",
                  "locationDenied" to "పికప్ కోసం లొకేషన్ అనుమతి ఇవ్వండి.",
                  "locationUnavailable" to
                          "మీ ప్రస్తుత స్థానం దొరకలేదు. లొకేషన్ చూసి మళ్లీ ప్రయత్నించండి.",
                  "retry" to "మళ్లీ ప్రయత్నించు",
                  "unknown" to "ఆ స్థలం సేవ్ చేయలేదు. క్రింద ఎంచుకోండి.",
                  "ambiguous" to "ఏ స్థలానికి వెళ్లాలి?",
                  "speechFailed" to "వినిపించలేదు. మళ్లీ చెప్పండి లేదా స్థలం నొక్కండి.",
                  "micDenied" to "మాట్లాడడానికి మైక్రోఫోన్ అనుమతి ఇవ్వండి, లేదా స్థలం నొక్కండి.",
                  "placeName" to "స్థలం పేరు",
                  "aliases" to "చెప్పే పేర్లు (కామాతో వేరు చేయండి)",
                  "search" to "చిరునామా వెతుకు",
                  "address" to "చిరునామా",
                  "checkMap" to "మ్యాప్‌లో గుర్తు చూసుకోండి",
                  "save" to "స్థలం సేవ్ చేయి",
                  "delete" to "స్థలం తొలగించు",
                  "duplicate" to "ఈ పేరు ఇప్పటికే ఉంది.",
                  "invalidPlace" to "ముందు వెతికి చిరునామా ఎంచుకోండి.",
                  "replaceHome" to "ఇల్లు తొలగించే ముందు కొత్త ఇల్లు జోడించండి.",
                  "edit" to "మార్చు",
                  "done" to "పూర్తయింది",
                  "demo" to "స్థలం లేదా మైక్రోఫోన్ నొక్కండి. నిర్ధారించి Uberలో బుక్ చేయండి.",
                  "handoffFailed" to "Uber తెరుచుకోలేదు. మళ్లీ ప్రయత్నించండి.",
                  "offline" to "వెతకడానికి ఇంటర్నెట్ కావాలి. తర్వాత ప్రయత్నించండి.",
                  "changeLanguage" to "భాష",
                  "manage" to "స్థలాలు మార్చు",
                  "back" to "వెనక్కి",
                  "configured" to "చిరునామా వెతుకులాట ఇంకా సిద్ధంగా లేదు.",
                  "choosePlace" to "సేవ్ చేసిన స్థలం ఎంచుకోండి",
                  "stop" to "వినడం ఆపు",
                  "wait" to "దయచేసి వేచి ఉండండి",
                  "voiceUnavailable" to "వాయిస్ సేవ లేదు. స్థలం నొక్కండి.",
                  "openLocation" to "లొకేషన్ సెట్టింగ్‌లు తెరువు",
                  "noResults" to "చిరునామా దొరకలేదు. మరింత వివరంగా వెతకండి.",
                  "mapAttribution" to "మ్యాప్ డేటా © OpenStreetMap సహకారులు",
                  "providerSettings" to "కుటుంబ సెటప్: మ్యాప్ సేవలు",
                  "searchService" to "చిరునామా శోధన సేవ URL",
                  "mapService" to "మ్యాప్ సేవ URL",
                  "invalidService" to "చెల్లుబాటు అయ్యే HTTPS సేవ URL ఇవ్వండి.",
                  "saveServices" to "సేవ URLలను సేవ్ చేయి",
                  "servicesSaved" to "సేవ URLలు సేవ్ అయ్యాయి.",
                  "mapUnavailable" to "మ్యాప్ లోడ్ కాలేదు. ఇంటర్నెట్ చూసి మళ్లీ ప్రయత్నించండి."
          )

  fun get(language: String, key: String): String =
          when (language) {
            "hi" -> hi[key]
            "te" -> te[key]
            else -> en[key]
          }
                  ?: en[key] ?: key
}
