package com.ridesaathi.app

object Words {
  private val en =
          mapOf(
                  "hello" to "Hello",
                  "setupHint" to "A little setup, for easier journeys. A family member can help you get started.",
                  "voiceHint" to "Tell us the name of a saved place.",
                  "tapHint" to "Or tap a place below to get started.",
                  "handoffHint" to "You’ll choose your ride and complete your booking in Uber.",
                  "welcome" to "Welcome to Ride Saathi",
                  "language" to "Choose your language",
                  "name" to "Your name",
                  "continue" to "Continue",
                  "homeRequired" to "Add your Home to continue",
                  "home" to "Home",
                  "addHome" to "Add Home",
                  "addPlace" to "Add saved place",
                  "finish" to "Finish setup",
                  "uberInstall" to "Install Uber before requesting a ride",
                  "install" to "Open Play Store",
                  "places" to "Saved places",
                  "settings" to "Settings",
                  "rideTo" to "Where do you want to go?",
                  "speak" to "Speak",
                  "listening" to "Listening…",
                  "recognizedSpeech" to "Recognized speech",
                  "heardSoFar" to "Heard so far…",
                  "cancel" to "Cancel",
                  "confirm" to "Is this your destination?",
                  "yes" to "Yes, open Uber",
                  "no" to "No, choose again",
                  "working" to "Getting your current location…",
                  "locationDenied" to "Allow location to set your pickup point.",
                  "locationUnavailable" to
                          "We could not get your current location. Check Location and try again.",
                  "retry" to "Try again",
                  "unknown" to "I could not find that saved place. Choose one below.",
                  "ambiguous" to "Which saved place did you mean?",
                  "speechFailed" to "I did not catch that. Try again or tap a place.",
                  "micDenied" to "Allow microphone access to speak, or tap a place below.",
                  "placeName" to "Place name",
                  "placeNameHint" to "Use the name you’ll say when asking for a ride.",
                  "editPlace" to "Edit place",
                  "changeAddress" to "Change address",
                  "selectAddress" to "Tap the correct address below.",
                  "openAppSettings" to "Open app permissions",
                  "storeUnavailable" to "Open the Play Store on your phone and search for Uber.",
                  "rideInterrupted" to "Ride request paused. Check the destination and try again.",
                  "search" to "Search address",
                  "addressSearchHint" to "Type at least 3 characters to search automatically.",
                  "searchPending" to "Search starts when you pause typing…",
                  "searchingAddress" to "Searching addresses…",
                  "address" to "Address",
                  "save" to "Save place",
                  "delete" to "Delete place",
                  "duplicate" to "This name is already used.",
                  "invalidPlace" to "Choose an address from search first.",
                  "replaceHome" to "Replace Home before removing it.",
                  "edit" to "Edit",
                  "done" to "Done",
                  "demo" to "Tap a place or the microphone. Confirm it, then finish in Uber.",
                  "handoffFailed" to "Uber could not open. Try again.",
                  "offline" to "Search needs internet. Try again later.",
                  "changeLanguage" to "Language",
                  "manage" to "Manage places",
                  "back" to "Back",
                  "configured" to "Address search is not set up yet. Ask the person who installed the app for help.",
                  "searchAttribution" to "Search powered by Ola Maps",
                  "searchAccessDenied" to "Address search could not connect to Ola Maps. Ask the person who installed the app for help.",
                  "searchQuota" to "Address search has reached its usage limit. Try again later.",
                  "searchUnavailable" to "Address search is temporarily unavailable. Please try again.",
                  "choosePlace" to "Choose a saved place",
                  "stop" to "Stop listening",
                  "wait" to "Please wait",
                  "voiceUnavailable" to "Voice service is unavailable. Tap a saved place.",
                  "openLocation" to "Open location settings",
                  "noResults" to "No matching address. Try a more specific search.",
                  "mapAttribution" to "Map data © OpenStreetMap",
                  "providerSettings" to "Family setup: map services",
                  "searchService" to "Address search service URL",
                  "mapService" to "Map preview service URL",
                  "invalidService" to "Enter valid HTTPS service URLs.",
                  "saveServices" to "Save service URLs",
                  "servicesSaved" to "Service URLs saved.",
                  "mapUnavailable" to "The map could not load. Check your connection and try again.",
                  "showMore" to "Show more",
                  "showLess" to "Show less",
                  "sharedLocation" to "Shared location",
                  "invalidSharedLocation" to "That message does not contain a supported location. Share a location or a Google Maps link with Ride Saathi.",
                  "sharedLocationSetup" to "Finish Ride Saathi setup before using a shared location.",
                  "resolvingSharedLocation" to "Opening shared location…",
                  "selectSharedLocation" to "Select the shared destination",
                  "sharedSearchHint" to "The link includes an address. Check these search results and select the correct place.",
                  "sharedLocationOffline" to "Could not open the Google Maps link. Check your internet connection and share it again.",
                  "sharedLocationUnresolved" to "Could not find a destination pin in that link. In Google Maps, select a place or drop a pin, then share it again."
          )
  private val hi =
          mapOf(
                  "searchAttribution" to "पते की खोज: Ola Maps",
                  "searchAccessDenied" to "Ola Maps से संपर्क नहीं हो सका। ऐप इंस्टॉल करने वाले व्यक्ति से मदद लें।",
                  "searchQuota" to "पते की खोज की उपयोग सीमा पूरी हो गई है। बाद में फिर कोशिश करें।",
                  "searchUnavailable" to "पते की खोज अभी उपलब्ध नहीं है। फिर कोशिश करें।",
                  "hello" to "नमस्ते",
                  "setupHint" to "आसान सफ़र के लिए छोटा सा सेटअप। परिवार का कोई सदस्य मदद कर सकता है।",
                  "voiceHint" to "चुनी गई जगह का नाम बोलें।",
                  "tapHint" to "या शुरू करने के लिए नीचे कोई जगह चुनें।",
                  "handoffHint" to "अपनी सवारी चुनें और बुकिंग Uber में पूरी करें।",
                  "welcome" to "राइड साथी में आपका स्वागत है",
                  "language" to "अपनी भाषा चुनें",
                  "name" to "आपका नाम",
                  "continue" to "आगे बढ़ें",
                  "homeRequired" to "आगे बढ़ने के लिए घर जोड़ें",
                  "home" to "घर",
                  "addHome" to "घर जोड़ें",
                  "addPlace" to "जगह जोड़ें",
                  "finish" to "सेटअप पूरा करें",
                  "uberInstall" to "यात्रा के लिए Uber इंस्टॉल करें",
                  "install" to "Play Store खोलें",
                  "places" to "चुनी गई जगहें",
                  "settings" to "सेटिंग्स",
                  "rideTo" to "आप कहाँ जाना चाहते हैं?",
                  "speak" to "चुनी गई जगह बोलें",
                  "listening" to "सुन रहे हैं…",
                  "recognizedSpeech" to "ऐप ने यह सुना",
                  "heardSoFar" to "अब तक सुना…",
                  "cancel" to "रद्द करें",
                  "confirm" to "क्या यही आपकी मंज़िल है?",
                  "yes" to "हाँ, Uber खोलें",
                  "no" to "नहीं, फिर चुनें",
                  "working" to "आपकी अभी की लोकेशन ढूँढ रहे हैं…",
                  "locationDenied" to "पिकअप के लिए आपकी अभी की लोकेशन चाहिए। इसकी अनुमति दें।",
                  "locationUnavailable" to
                          "आपकी अभी की लोकेशन नहीं मिली। लोकेशन चेक करें और फिर कोशिश करें।",
                  "retry" to "फिर कोशिश करें",
                  "unknown" to "यह जगह चुनी हुई जगहों में नहीं है। नीचे से चुनें।",
                  "ambiguous" to "आप किस जगह जाना चाहते हैं?",
                  "speechFailed" to "आवाज़ समझ नहीं आई। फिर बोलें या जगह चुनें।",
                  "micDenied" to "बोलने के लिए माइक्रोफ़ोन की अनुमति दें, या नीचे से जगह चुनें।",
                  "placeName" to "जगह का नाम",
                  "placeNameHint" to "वह नाम लिखें जो आप सवारी माँगते समय बोलेंगे।",
                  "editPlace" to "जगह बदलें",
                  "changeAddress" to "पता बदलें",
                  "selectAddress" to "नीचे सही पते पर टैप करें।",
                  "openAppSettings" to "ऐप की अनुमतियाँ खोलें",
                  "storeUnavailable" to "अपने फ़ोन पर Play Store खोलें और Uber खोजें।",
                  "rideInterrupted" to "यात्रा का अनुरोध रुक गया। जगह जाँचें और फिर कोशिश करें।",
                  "search" to "पता खोजें",
                  "addressSearchHint" to "अपने आप खोजने के लिए कम से कम 3 अक्षर लिखें।",
                  "searchPending" to "आपके लिखना रोकने पर खोज शुरू होगी…",
                  "searchingAddress" to "पते खोज रहे हैं…",
                  "address" to "पता",
                  "save" to "जगह सेव करें",
                  "delete" to "जगह हटाएँ",
                  "duplicate" to "यह नाम पहले से है।",
                  "invalidPlace" to "पहले खोज में से कोई पता चुनें।",
                  "replaceHome" to "घर हटाने से पहले नया घर जोड़ें।",
                  "edit" to "बदलें",
                  "done" to "हो गया",
                  "demo" to "जगह या माइक्रोफ़ोन दबाएँ। कन्फर्म करें, फिर Uber में बुक करें।",
                  "handoffFailed" to "Uber नहीं खुला। फिर कोशिश करें।",
                  "offline" to "खोज के लिए इंटरनेट चाहिए। बाद में कोशिश करें।",
                  "changeLanguage" to "भाषा",
                  "manage" to "जगहें बदलें",
                  "back" to "वापस",
                  "configured" to "पता खोज अभी सेट नहीं है।",
                  "choosePlace" to "चुनी गई जगह चुनें",
                  "stop" to "सुनना बंद करें",
                  "wait" to "कृपया प्रतीक्षा करें",
                  "voiceUnavailable" to "आवाज़ की सुविधा नहीं चल रही। नीचे से जगह चुनें।",
                  "openLocation" to "लोकेशन सेटिंग्स खोलें",
                  "noResults" to "पता नहीं मिला। अधिक जानकारी लिखकर खोजें।",
                  "mapAttribution" to "नक्शे का डेटा © OpenStreetMap योगदानकर्ता",
                  "providerSettings" to "परिवार सेटअप: नक्शा सेवाएँ",
                  "searchService" to "पता खोज सेवा URL",
                  "mapService" to "नक्शा सेवा URL",
                  "invalidService" to "मान्य HTTPS सेवा URL डालें।",
                  "saveServices" to "सेवा URL सेव करें",
                  "servicesSaved" to "सेवा URL सेव हो गए।",
                  "mapUnavailable" to "नक्शा नहीं खुला। इंटरनेट चेक करें और फिर कोशिश करें।",
                  "showMore" to "और देखें",
                  "showLess" to "कम देखें",
                  "sharedLocation" to "शेयर की गई लोकेशन",
                  "invalidSharedLocation" to "इस संदेश में लोकेशन नहीं मिली। Ride Saathi के साथ लोकेशन या Google Maps लिंक शेयर करें।",
                  "sharedLocationSetup" to "शेयर की गई लोकेशन इस्तेमाल करने से पहले Ride Saathi का सेटअप पूरा करें।",
                  "resolvingSharedLocation" to "शेयर की गई लोकेशन खोली जा रही है…",
                  "selectSharedLocation" to "शेयर की गई मंज़िल चुनें",
                  "sharedSearchHint" to "लिंक में पता मिला है। खोज के नतीजे जाँचें और सही जगह चुनें।",
                  "sharedLocationOffline" to "Google Maps लिंक नहीं खुल सका। इंटरनेट कनेक्शन जाँचें और फिर से शेयर करें।",
                  "sharedLocationUnresolved" to "इस लिंक में मंज़िल का पिन नहीं मिला। Google Maps में कोई जगह चुनें या पिन लगाएँ, फिर से शेयर करें।"
          )
  // Archived for future Telugu support; intentionally excluded from get().
  private val te =
          mapOf(
                  "hello" to "నమస్కారం",
                  "setupHint" to "సులభమైన ప్రయాణాల కోసం చిన్న సెటప్. కుటుంబ సభ్యులు సహాయం చేయవచ్చు.",
                  "voiceHint" to "సేవ్ చేసిన స్థలం పేరు చెప్పండి.",
                  "tapHint" to "లేదా ప్రారంభించడానికి క్రింద ఒక స్థలాన్ని నొక్కండి.",
                  "handoffHint" to "మీ రైడ్ ఎంచుకుని Uberలో బుకింగ్ పూర్తి చేయండి.",
                  "welcome" to "రైడ్ సాథికి స్వాగతం",
                  "language" to "మీ భాషను ఎంచుకోండి",
                  "name" to "మీ పేరు",
                  "continue" to "కొనసాగించు",
                  "homeRequired" to "ముందుకు వెళ్లడానికి ఇల్లు జోడించండి",
                  "home" to "ఇల్లు",
                  "addHome" to "ఇల్లు జోడించు",
                  "addPlace" to "స్థలం జోడించు",
                  "finish" to "సెటప్ పూర్తి చేయి",
                  "uberInstall" to "రైడ్ కోసం Uber ఇన్‌స్టాల్ చేయండి",
                  "install" to "Play Store తెరువు",
                  "places" to "సేవ్ చేసిన స్థలాలు",
                  "settings" to "సెట్టింగ్‌లు",
                  "rideTo" to "మీరు ఎక్కడికి వెళ్లాలి?",
                  "speak" to "సేవ్ చేసిన స్థలాన్ని చెప్పండి",
                  "listening" to "వింటున్నాం…",
                  "recognizedSpeech" to "యాప్ విన్న మాటలు",
                  "heardSoFar" to "ఇప్పటివరకు విన్నది…",
                  "cancel" to "రద్దు",
                  "confirm" to "ఇదే మీ గమ్యస్థానమా?",
                  "yes" to "అవును, Uber తెరువు",
                  "no" to "కాదు, మళ్లీ ఎంచుకోండి",
                  "working" to "మీ ప్రస్తుత స్థానం చూస్తున్నాం…",
                  "locationDenied" to "పికప్ కోసం లొకేషన్ అనుమతి ఇవ్వండి.",
                  "locationUnavailable" to
                          "మీ ప్రస్తుత స్థానం దొరకలేదు. లొకేషన్ చూసి మళ్లీ ప్రయత్నించండి.",
                  "retry" to "మళ్లీ ప్రయత్నించు",
                  "unknown" to "ఆ స్థలం సేవ్ చేయలేదు. క్రింద ఎంచుకోండి.",
                  "ambiguous" to "ఏ స్థలానికి వెళ్లాలి?",
                  "speechFailed" to "వినిపించలేదు. మళ్లీ చెప్పండి లేదా స్థలం నొక్కండి.",
                  "micDenied" to "మాట్లాడడానికి మైక్రోఫోన్ అనుమతి ఇవ్వండి, లేదా స్థలం నొక్కండి.",
                  "placeName" to "స్థలం పేరు",
                  "search" to "చిరునామా వెతుకు",
                  "address" to "చిరునామా",
                  "save" to "స్థలం సేవ్ చేయి",
                  "delete" to "స్థలం తొలగించు",
                  "duplicate" to "ఈ పేరు ఇప్పటికే ఉంది.",
                  "invalidPlace" to "ముందు వెతికి చిరునామా ఎంచుకోండి.",
                  "replaceHome" to "ఇల్లు తొలగించే ముందు కొత్త ఇల్లు జోడించండి.",
                  "edit" to "మార్చు",
                  "done" to "పూర్తయింది",
                  "demo" to "స్థలం లేదా మైక్రోఫోన్ నొక్కండి. నిర్ధారించి Uberలో బుక్ చేయండి.",
                  "handoffFailed" to "Uber తెరుచుకోలేదు. మళ్లీ ప్రయత్నించండి.",
                  "offline" to "వెతకడానికి ఇంటర్నెట్ కావాలి. తర్వాత ప్రయత్నించండి.",
                  "changeLanguage" to "భాష",
                  "manage" to "స్థలాలు మార్చు",
                  "back" to "వెనక్కి",
                  "configured" to "చిరునామా వెతుకులాట ఇంకా సిద్ధంగా లేదు.",
                  "choosePlace" to "సేవ్ చేసిన స్థలం ఎంచుకోండి",
                  "stop" to "వినడం ఆపు",
                  "wait" to "దయచేసి వేచి ఉండండి",
                  "voiceUnavailable" to "వాయిస్ సేవ లేదు. స్థలం నొక్కండి.",
                  "openLocation" to "లొకేషన్ సెట్టింగ్‌లు తెరువు",
                  "noResults" to "చిరునామా దొరకలేదు. మరింత వివరంగా వెతకండి.",
                  "mapAttribution" to "మ్యాప్ డేటా © OpenStreetMap సహకారులు",
                  "providerSettings" to "కుటుంబ సెటప్: మ్యాప్ సేవలు",
                  "searchService" to "చిరునామా శోధన సేవ URL",
                  "mapService" to "మ్యాప్ సేవ URL",
                  "invalidService" to "చెల్లుబాటు అయ్యే HTTPS సేవ URL ఇవ్వండి.",
                  "saveServices" to "సేవ URLలను సేవ్ చేయి",
                  "servicesSaved" to "సేవ URLలు సేవ్ అయ్యాయి.",
                  "mapUnavailable" to "మ్యాప్ లోడ్ కాలేదు. ఇంటర్నెట్ చూసి మళ్లీ ప్రయత్నించండి.",
                  "showMore" to "మరింత చూడండి",
                  "showLess" to "తక్కువగా చూడండి"
          )

  fun get(language: String, key: String): String =
          when (language) {
            "hi" -> hi[key]
            else -> en[key]
          }
                  ?: en[key] ?: key
}
